[project]
name = "fastrtc-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastrtc[stt,vad]>=0.0.34",
    "kokoro-onnx>=0.4.9",
    "langgraph>=1.0.6",
    "numpy>=2.3.5",
    "openai>=2.15.0",
    "pydub>=0.25.1",
]
